mini:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
#    host: mysql
    port: "3306"
    database: mini_order
    username: root
    password: "123456"

  wechat:
    appid: wx8537ec100754afa3
    secret: 15c2291060dde0c80c337e2d27860c0b